config/routes.rb
Rails.application.routes.draw do
  #get 'file_uploads/new'
  resources :posts do
    resources :file_uploads, only: [:new, :create, :destroy]
  end
  resources :contests
  resources :imagems
  resources :commercials
  resources :salaries
  resources :cities
  devise_for :users
  resources :event_attachments
  authenticated :user do
    resources :events, as: :authenticated_root
  end

  resources :events
  get 'home/index'
  root 'home#index'

  mount Ckeditor::Engine => '/ckeditor'
  resources :ckeditor
  resources :jobs
  resources :capacities
  resources :sectors
  resources :classifields
  resources :category_classifieds
  resources :posts
  resources :categories
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
         can :manage, :all
       else
         can :read, :all
         can :manage, Classifield, user_id: user.id 
         can :manage, Job, user_id: user.id
         can [:read], Post
         can [:read], Event
         can [:read], Contest
         can [:read], Commercial
         can :manage, User, id: user.id
       end
       
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/capacity.rb
class Capacity < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :user
end

app/models/classifield.rb
class Classifield < ApplicationRecord
  belongs_to :user
  belongs_to :city
  

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many_attached :images
end

app/models/commercial.rb
class Commercial < ApplicationRecord
  belongs_to :user
  belongs_to :city
  belongs_to :category
  has_many_attached :images
 
end

app/models/contest.rb
class Contest < ApplicationRecord
  belongs_to :user
  belongs_to :city
 

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_one_attached :image
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :city
   
    
    #has_many :event_attachments, dependent: :destroy
    #accepts_nested_attributes_for :event_attachments
    has_one_attached :image
    has_many_attached :images
    extend FriendlyId
    friendly_id :title, use: :slugged
    
end

app/models/imagem.rb
class Imagem < ApplicationRecord
   
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  belongs_to :sector
  belongs_to :capacity
  belongs_to :salary
  has_one :city
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_one_attached :image
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/salary.rb
class Salary < ApplicationRecord
end

app/models/sector.rb
class Sector < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    extend FriendlyId
  friendly_id :name, use: :slugged

  
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_avatar
  
  def crop_avatar
    avatar.recreate_versions! if crop_x.present?
  end
  has_one :city
  has_one_attached :image

  #def image_nil
   # if !self.image?
    #    user.image.attach(io: File.open('/path/to/file'), filename: 'default.jpg', content_type: 'image/jpeg')
    #end
  #end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
    @posts = Post.where.not(category: 3).last(3)
    @events = Event.where(role: 1).order("date")
    @esportes = Post.where(category: 3).order("created_at DESC").last(4)
    @classifields = Classifield.last(6)
    @jobs = Job.last(8)
    @commercials = Commercial.where(role: 1)
    @contests = Contest.last(8)
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/imagems_helper.rb
module ImagemsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_form.html.erb
  <div class="col s12 m6 l6">
    <%= link_to @posts.third do %>
      <div class="card " >
        <div class="card-image ">
        <%= image_tag (@posts.third.image) %> 
          <span class="card-title text-h"><%= @posts.third.title %></span>
          
        </div> 
      </div>
    <% end %>
  </div>
  <div class="col s12 m6 l6">
  <div class="row">
   <div class="col s12 m12 l12">
    <%= link_to @posts.second do %>
      <div class="card horizontal">
        <div class="card-image">
        <%= image_tag @posts.second.image %> 
        </div> 
        <div class="card-stacked">
          <div class="card-content">
          <p class="red-text text-darken-2"><%= @posts.second.category.title%> </p>
          <span class="sub2  grey-text text-darken-4"><%= @posts.second.title[0..35]%></span>
          <p class="red-text text-darken-2"> <%= time_ago_in_words(@posts.second.created_at) %></p> 
          </div>
        </div>
      </div>
    <% end %>
  </div>

   <div class="col s12 m12 l12">
    <%= link_to @posts.first do %>
      <div class="card horizontal">
        <div class="card-image">
        <%= image_tag @posts.first.image %> 
        </div> 
        <div class="card-stacked">
          <div class="card-content">
            <p class="red-text text-darken-2"><%= @posts.first.category.title%> </p>
            <span class="sub2 activator grey-text text-darken-4"><%= @posts.first.title[0..35]%></span> 
            <p class="red-text text-darken-2"> <%= time_ago_in_words(@posts.first.created_at) %></p>
          </div>  
        </div>
      </div>
    <% end %>
  </div>

</div>        
</div>  

app/views/home/_form2.html.erb
 
<% @esportes.each do |post| %>
    <div class="col s12 m6 l3">   
    <%= link_to post do %> 
      <div class="card small">
        <div class="card-image image">
        <%= image_tag post.image %> 
        </div> 
        <div class="card-content">
        <p class="green-text text-darken-2"><%= post.category.title%> </p>
          <span class="sub2 activator grey-text text-darken-4"><%= post.title %></span>
        <p class="green-text text-darken-2"> <%= time_ago_in_words(post.created_at) %></p>
        </div> 
      </div> 
      <% end %>     
    </div>
<% end %> 

app/views/home/_form3.html.erb
<% @classifields.each do |post| %>
    <div class="col s12 m12 l3">   
    <%= link_to post do %> 
      <div class="card small">
        <div class="card-image image">
        <%= image_tag post.images[0] %> 
        </div> 
        <div class="card-content">
          <p class="sub2 activator green-text text-darken-4">R$ <%= post.value %></p>
          <span class="sub2 activator grey-text text-darken-4"><%= post.title %></span>
        </div>
         
      </div> 
      <% end %>     
    </div>
    <% end %>

app/views/home/_form4.html.erb
<% @jobs.each do |job| %>
  <div class="col s12 m6 l3">  
  <%= link_to job do %> 
      <div class="card small">
        <div class="card-image image">
        <%= image_tag job.user.image %> 
        </div> 
        <div class="card-content">
          <span class="sub2 activator grey-text text-darken-4"><%= job.title %></span>
          <p class=""><%= job.sector.title %></p>
        </div>
        <div class="card-action center">
            <span class="blue-text text-darken-2">maringa </span> - 
            <span class="blue-text text-darken-2"> <%= time_ago_in_words(job.created_at) %></span>
        </div>
         
      </div> 
      <% end %>  
  </div>
  <% end %>

app/views/home/_form5.html.erb
 <% @commercials.each do |post| %>
    <div class="col s12 m12 l4">   
    <%= link_to post do %> 
      <div class="card small">
        <div class="card-image image">
          <%= image_tag post.images[0] %>  
        </div> 

        <div class="card-content">
          <p class="sub2 activator grey-text text-darken-4"><%= post.title %></p>
          <p class="grey-text"><%= post.category.title %></p>
          <p class="grey-text"><%= post.city.description %></p>
        </div>
         
      </div> 
      <% end %>     
    </div>
    <% end %>

app/views/home/_form6.html.erb
 <% @contests.each do |post| %>
    <div class="col s12 m12 l4">   
    <%= link_to post do %> 
      <div class="card small">
        <div class="card-image image">
          <%= image_tag post.image %>  
        </div> 

        <div class="card-content">
          <span class="sub2 activator grey-text text-darken-4"><%= post.title %></span>
          <p class="red-text text-darken-2 sub2">Inscrições até <%= post.date.to_formatted_s(:short) %> </p>
          <p class="grey-text text-darken-2"><%= post.city.description %> </p>
          <span class="grey-text text-darken-2"> <%= time_ago_in_words(post.created_at) %></span>
        </div>
         
      </div> 
      <% end %>     
    </div>
    <% end %>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
 
 <div class="slider">
    <ul class="slides">
    <% @events.each do |event| %>
      <li>
        <%= link_to event do %>
          <%= image_tag event.image,width:"100%" %> <!-- random image -->
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

  
     

<div class="row">
  <h1 class="header red-text text-darken-2">Últimas Notícias meesmo</h1>
   <div class="divider red darken-2 "></div>
  <%= render 'form', post: @post %>
  <%= link_to posts_path do %> 
  <h5 class="link-mais orange-text right">+ Notícias</h5>
<% end %>
</div> 
<div >
 <!-- LOMADEE - BEGIN -->
<script src="//ad.lomadee.com/banners/script.js?sourceId=35984927&dimension=4&height=250&width=300&method=1&advertisers=6111,5798,6160,5840,5860,5766" type="text/javascript" language="javascript"></script>
<!-- LOMADEE - END -->
</div>
    
<div class="row">
<h1 class="header green-text text-darken-2">Esporte</h1>
<div class="divider green darken-2"> </div>
 <%= render 'form2' %>
 <%= link_to posts_path do %> 
  <h5 class="link-mais orange-text right">+ Esporte</h5>
<% end %>
</div>

<!-- LOMADEE - BEGIN -->
<script src="//ad.lomadee.com/banners/script.js?sourceId=35984927&dimension=1&height=90&width=728&method=1&advertisers=5632,6111,5731,5798,5860" type="text/javascript" language="javascript"></script>
<!-- LOMADEE - END -->
<div class="row">
<h1 class="header orange-text text-darken-2">Classificados</h1>
 <div class="divider orange darken-2"> </div>
 <%= render 'form3' %>
 <%= link_to classifields_path do %> 
  <h5 class="link-mais orange-text right">+ Classificados</h5>
<% end %>
</div>

<!-- Vitrine Inteligente Lomadee -->
<div class="g3S6Z4x927jE" style="width: 970px; height: 250px">
<script type="text/javascript" class="lomadee-recommender-script" src="//ad.lomadee.com/v1/eyJwdWJsaXNoZXJJZCI6MjI3NjU1MjgsInNpdGVJZCI6MzM5MjIwODIsInNvdXJjZUlkIjozNTg3NDcwNX0%3D.js?w=970&h=250"></script>
</div><!-- Vitrine Inteligente Lomadee -->


<div class="row">
<h1 class="header blue-text text-darken-2">Emprego</h1>
<div class="divider blue darken-2"> </div>
 <%= render 'form4', post: @jobs %>
 <%= link_to jobs_path do %> 
  <h5 class="link-mais blue-text text-darken-2 right">+ Empregos</h5>
<% end %>
</div>

<div>
<!-- LOMADEE - BEGIN -->
<script src="//ad.lomadee.com/banners/script.js?sourceId=35984927&dimension=1&height=90&width=728&method=1&advertisers=5632,6111,5731,5798,5860" type="text/javascript" language="javascript"></script>
<!-- LOMADEE - END -->

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-9835055996289480",
          enable_page_level_ads: true
     });
</script>
<div class="row">
<h1 class="header orange-text text-darken-2">Guia Comercial</h1>
<div class="divider orange darken-2"> </div>
 <%= render 'form5' %>
 <%= link_to commercials_path do %> 
  <h5 class="link-mais blue-text text-darken-2 right">+ Comercios</h5>
<% end %>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-9835055996289480",
          enable_page_level_ads: true
     });
</script>


<!-- LOMADEE - BEGIN -->
<script src="//ad.lomadee.com/banners/script.js?sourceId=35984927&dimension=9&height=350&width=350&method=0" type="text/javascript" language="javascript"></script>
<!-- LOMADEE - END -->


<div class="row">
<h1 class="header blue-text text-darken-4">Concursos Público</h1>
<div class="divider blue darken-4"> </div>
 <%= render 'form6' %>
 <%= link_to contests_path do %> 
  <h5 class="link-mais blue-text text-darken-4 right">+ Concursos</h5>
<% end %>
</div>
<!-- LOMADEE - BEGIN -->
<script src="//ad.lomadee.com/banners/script.js?sourceId=35984927&dimension=1&height=90&width=728&method=1&advertisers=5632,6111,5731,5798,5860" type="text/javascript" language="javascript"></script>
<!-- LOMADEE - END -->