config/routes.rb
Rails.application.routes.draw do
  #get 'file_uploads/new'
  resources :posts do
    resources :file_uploads, only: [:new, :create, :destroy]
  end
  resources :contests
  resources :imagems
  resources :commercials
  resources :salaries
  resources :cities
  devise_for :users
  resources :event_attachments
  authenticated :user do
    resources :events, as: :authenticated_root
  end

  resources :events
  get 'home/index'
  root 'home#index'

  mount Ckeditor::Engine => '/ckeditor'
  resources :ckeditor
  resources :jobs
  resources :capacities
  resources :sectors
  resources :classifields
  resources :category_classifieds
  resources :posts
  resources :categories
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
         can :manage, :all
       else
         can :read, :all
         can :manage, Classifield, user_id: user.id 
         can :manage, Job, user_id: user.id
         can [:read], Post
         can [:read], Event
         can [:read], Contest
         can [:read], Commercial
         can :manage, User, id: user.id
       end
       
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/capacity.rb
class Capacity < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :user
end

app/models/classifield.rb
class Classifield < ApplicationRecord
  belongs_to :user
  belongs_to :city
  

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many_attached :images
end

app/models/commercial.rb
class Commercial < ApplicationRecord
  belongs_to :user
  belongs_to :city
  belongs_to :category
  has_many_attached :images
 
end

app/models/contest.rb
class Contest < ApplicationRecord
  belongs_to :user
  belongs_to :city
 

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_one_attached :image
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :city
   
    
    #has_many :event_attachments, dependent: :destroy
    #accepts_nested_attributes_for :event_attachments
    has_one_attached :image
    has_many_attached :images
    extend FriendlyId
    friendly_id :title, use: :slugged
    
end

app/models/imagem.rb
class Imagem < ApplicationRecord
   
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  belongs_to :sector
  belongs_to :capacity
  belongs_to :salary
  has_one :city
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_one_attached :image
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/salary.rb
class Salary < ApplicationRecord
end

app/models/sector.rb
class Sector < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    extend FriendlyId
  friendly_id :name, use: :slugged

  
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_avatar
  
  def crop_avatar
    avatar.recreate_versions! if crop_x.present?
  end
  has_one :city
  has_one_attached :image

  #def image_nil
   # if !self.image?
    #    user.image.attach(io: File.open('/path/to/file'), filename: 'default.jpg', content_type: 'image/jpeg')
    #end
  #end


end

app/controllers/capacities_controller.rb
class CapacitiesController < ApplicationController
  before_action :set_capacity, only: [:show, :edit, :update, :destroy]

  # GET /capacities
  # GET /capacities.json
  def index
    @capacities = Capacity.all
  end

  # GET /capacities/1
  # GET /capacities/1.json
  def show
  end

  # GET /capacities/new
  def new
    @capacity = Capacity.new
  end

  # GET /capacities/1/edit
  def edit
  end

  # POST /capacities
  # POST /capacities.json
  def create
    @capacity = Capacity.new(capacity_params)

    respond_to do |format|
      if @capacity.save
        format.html { redirect_to @capacity, notice: 'Capacity was successfully created.' }
        format.json { render :show, status: :created, location: @capacity }
      else
        format.html { render :new }
        format.json { render json: @capacity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /capacities/1
  # PATCH/PUT /capacities/1.json
  def update
    respond_to do |format|
      if @capacity.update(capacity_params)
        format.html { redirect_to @capacity, notice: 'Capacity was successfully updated.' }
        format.json { render :show, status: :ok, location: @capacity }
      else
        format.html { render :edit }
        format.json { render json: @capacity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /capacities/1
  # DELETE /capacities/1.json
  def destroy
    @capacity.destroy
    respond_to do |format|
      format.html { redirect_to capacities_url, notice: 'Capacity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_capacity
      @capacity = Capacity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def capacity_params
      params.require(:capacity).permit(:user_id, :title)
    end
end

app/helpers/capacities_helper.rb
module CapacitiesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/imagems_helper.rb
module ImagemsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/capacities/_form.html.erb
<%= form_with(model: capacity, local: true) do |form| %>
  <% if capacity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(capacity.errors.count, "error") %> prohibited this capacity from being saved:</h2>

      <ul>
      <% capacity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :capacity_user_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :capacity_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/capacities/edit.html.erb
<h1>Editing Capacity</h1>

<%= render 'form', capacity: @capacity %>

<%= link_to 'Show', @capacity %> |
<%= link_to 'Back', capacities_path %>

app/views/capacities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Capacities</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @capacities.each do |capacity| %>
      <tr>
        <td><%= capacity.user %></td>
        <td><%= capacity.title %></td>
        <td><%= link_to 'Show', capacity %></td>
        <td><%= link_to 'Edit', edit_capacity_path(capacity) %></td>
        <td><%= link_to 'Destroy', capacity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Capacity', new_capacity_path %>

app/views/capacities/new.html.erb
<h1>New Capacity</h1>

<%= render 'form', capacity: @capacity %>

<%= link_to 'Back', capacities_path %>

app/views/capacities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @capacity.user %>
</p>

<p>
  <strong>Title:</strong>
  <%= @capacity.title %>
</p>

<%= link_to 'Edit', edit_capacity_path(@capacity) %> |
<%= link_to 'Back', capacities_path %>