config/routes.rb
Rails.application.routes.draw do
  #get 'file_uploads/new'
  resources :posts do
    resources :file_uploads, only: [:new, :create, :destroy]
  end
  resources :contests
  resources :imagems
  resources :commercials
  resources :salaries
  resources :cities
  devise_for :users
  resources :event_attachments
  authenticated :user do
    resources :events, as: :authenticated_root
  end

  resources :events
  get 'home/index'
  root 'home#index'

  mount Ckeditor::Engine => '/ckeditor'
  resources :ckeditor
  resources :jobs
  resources :capacities
  resources :sectors
  resources :classifields
  resources :category_classifieds
  resources :posts
  resources :categories
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
         can :manage, :all
       else
         can :read, :all
         can :manage, Classifield, user_id: user.id 
         can :manage, Job, user_id: user.id
         can [:read], Post
         can [:read], Event
         can [:read], Contest
         can [:read], Commercial
         can :manage, User, id: user.id
       end
       
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/capacity.rb
class Capacity < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :user
end

app/models/classifield.rb
class Classifield < ApplicationRecord
  belongs_to :user
  belongs_to :city
  

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many_attached :images
end

app/models/commercial.rb
class Commercial < ApplicationRecord
  belongs_to :user
  belongs_to :city
  belongs_to :category
  has_many_attached :images
 
end

app/models/contest.rb
class Contest < ApplicationRecord
  belongs_to :user
  belongs_to :city
 

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_one_attached :image
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :city
   
    
    #has_many :event_attachments, dependent: :destroy
    #accepts_nested_attributes_for :event_attachments
    has_one_attached :image
    has_many_attached :images
    extend FriendlyId
    friendly_id :title, use: :slugged
    
end

app/models/event_attachment.rb
class EventAttachment < ApplicationRecord
  belongs_to :event
  
end

app/models/imagem.rb
class Imagem < ApplicationRecord
   
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  belongs_to :sector
  belongs_to :capacity
  belongs_to :salary
  has_one :city
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_one_attached :image
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/salary.rb
class Salary < ApplicationRecord
end

app/models/sector.rb
class Sector < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    extend FriendlyId
  friendly_id :name, use: :slugged

  
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_avatar
  
  def crop_avatar
    avatar.recreate_versions! if crop_x.present?
  end
  has_one :city
  has_one_attached :image

  #def image_nil
   # if !self.image?
    #    user.image.attach(io: File.open('/path/to/file'), filename: 'default.jpg', content_type: 'image/jpeg')
    #end
  #end


end

app/controllers/event_attachments_controller.rb
class EventAttachmentsController < ApplicationController
  before_action :set_event_attachment, only: [:show, :edit, :update, :destroy]

  # GET /event_attachments
  # GET /event_attachments.json
  def index
    @event_attachments = EventAttachment.all
  end

  # GET /event_attachments/1
  # GET /event_attachments/1.json
  def show
  end

  # GET /event_attachments/new
  def new
    @event_attachment = EventAttachment.new
  end

  # GET /event_attachments/1/edit
  def edit
  end

  # POST /event_attachments
  # POST /event_attachments.json
  def create
    @event_attachment = EventAttachment.new(event_attachment_params)

    respond_to do |format|
      if @event_attachment.save
        format.html { redirect_to @event_attachment, notice: 'Event attachment was successfully created.' }
        format.json { render :show, status: :created, location: @event_attachment }
      else
        format.html { render :new }
        format.json { render json: @event_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_attachments/1
  # PATCH/PUT /event_attachments/1.json
  def update
    respond_to do |format|
      if @event_attachment.update(event_attachment_params)
        format.html { redirect_to @event_attachment, notice: 'Event attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_attachment }
      else
        format.html { render :edit }
        format.json { render json: @event_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_attachments/1
  # DELETE /event_attachments/1.json
  def destroy
    @event_attachment.destroy
    respond_to do |format|
      format.html { redirect_to event_attachments_url, notice: 'Event attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_attachment
      @event_attachment = EventAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_attachment_params
      params.require(:event_attachment).permit(:event_id, :avatar)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/event_attachments_helper.rb
module EventAttachmentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_attachments/_form.html.erb
<%= form_with(model: event_attachment, local: true) do |form| %>
  <% if event_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_attachment.errors.count, "error") %> prohibited this event_attachment from being saved:</h2>

      <ul>
      <% event_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id, id: :event_attachment_event_id %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.text_field :avatar, id: :event_attachment_avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_attachments/edit.html.erb
<h1>Editing Event Attachment</h1>

<%= render 'form', event_attachment: @event_attachment %>

<%= link_to 'Show', @event_attachment %> |
<%= link_to 'Back', event_attachments_path %>

app/views/event_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_attachments.each do |event_attachment| %>
      <tr>
        <td><%= event_attachment.event.title %></td>
        <td><%= image_tag (event_attachment.avatar_url),width:"25%" %></td>
        <td><%= link_to 'Show', event_attachment %></td>
        <td><%= link_to 'Edit', edit_event_attachment_path(event_attachment) %></td>
        <td><%= link_to 'Destroy', event_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event Attachment', new_event_attachment_path %>

app/views/event_attachments/new.html.erb
<h1>New Event Attachment</h1>

<%= render 'form', event_attachment: @event_attachment %>

<%= link_to 'Back', event_attachments_path %>

app/views/event_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @event_attachment.event %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @event_attachment.avatar %>
</p>

<%= link_to 'Edit', edit_event_attachment_path(@event_attachment) %> |
<%= link_to 'Back', event_attachments_path %>